name: latihan_pdf_viewer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  flutter_pdfview: ^1.2.1
  get: 4.6.1
  http: ^0.13.4
  path_provider: ^2.0.8
  share_plus: 3.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

